final model:
- name: XGboost Classifier
    params:
      n_estimators: 200
      max_depth: 15
      subsample: 0.9
      learning_rate: 0.04
      reg_lambda: 0.3
      reg_alpha: 0.05
      gamma: 0.1
      colsample_bytree: 0.9
      
